# Generated by Django 2.2.1 on 2019-08-29 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_id', models.CharField(db_index=True, max_length=64)),
                ('choice_txt', models.CharField(max_length=2000)),
                ('created_user_id', models.CharField(max_length=250)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_user_id', models.CharField(max_length=250)),
                ('last_updated_timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'choice_bank',
            },
        ),
        migrations.CreateModel(
            name='QuestionTypeList',
            fields=[
                ('question_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_type_txt', models.CharField(max_length=200)),
                ('created_user_id', models.CharField(max_length=250)),
                ('created_timestamp', models.DateTimeField(auto_now=True)),
                ('updated_user_id', models.CharField(max_length=250)),
                ('last_updated_timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'question_type_list',
            },
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_txt', models.CharField(max_length=2000)),
                ('answer_id', models.CharField(max_length=30)),
                ('choice_50_50', models.CharField(max_length=30)),
                ('remaining_choice', models.CharField(default=None, max_length=30)),
                ('created_user_id', models.CharField(max_length=250)),
                ('created_timestamp', models.DateTimeField(auto_now=True)),
                ('updated_user_id', models.CharField(max_length=250)),
                ('last_updated_timestamp', models.DateTimeField(auto_now=True)),
                ('question_type_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='QuestionManagement.QuestionTypeList')),
            ],
            options={
                'db_table': 'question_bank',
            },
        ),
    ]
