# Generated by Django 2.2.1 on 2019-08-20 04:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_id', models.CharField(max_length=20)),
                ('choice_txt', models.CharField(max_length=250)),
                ('created_user_id', models.CharField(max_length=250)),
                ('created_timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_user_id', models.CharField(max_length=250)),
                ('last_updated_timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'choice_bank',
            },
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=50, unique=True)),
                ('question_type_id', models.CharField(max_length=25)),
                ('question_txt', models.CharField(max_length=260)),
                ('answer_id', models.CharField(max_length=20)),
                ('choice_50_50', models.CharField(max_length=20)),
                ('created_user_id', models.CharField(max_length=250)),
                ('created_timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_user_id', models.CharField(max_length=250)),
                ('last_updated_timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'question_bank',
            },
        ),
        migrations.CreateModel(
            name='QuestionTypeList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type_txt', models.CharField(max_length=20)),
                ('created_user_id', models.CharField(max_length=250)),
                ('created_timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_user_id', models.CharField(max_length=250)),
                ('last_updated_timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('choice_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='QuestionManagement.ChoiceBank')),
                ('question_type_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='QuestionManagement.QuestionBank')),
            ],
            options={
                'db_table': 'question_type_list',
            },
        ),
    ]
