# Generated by Django 2.2.1 on 2019-08-21 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionManagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiontypelist',
            name='choice_id',
        ),
        migrations.AddField(
            model_name='questionbank',
            name='remaining_choice',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='choicebank',
            name='choice_id',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='choicebank',
            name='choice_txt',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='answer_id',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='choice_50_50',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='question_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='question_txt',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='question_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='QuestionManagement.QuestionTypeList'),
        ),
        migrations.AlterField(
            model_name='questiontypelist',
            name='question_type_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='questiontypelist',
            name='question_type_txt',
            field=models.CharField(max_length=200),
        ),
    ]
