# Generated by Django 2.2.1 on 2019-08-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionManagement', '0002_auto_20190821_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbank',
            name='remaining_choice',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
