# Generated by Django 2.2.1 on 2019-08-20 04:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('QuestionManagement', '0001_initial'),
        ('UserManagement', '0002_auto_20190820_0832'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplexityList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complexity_id', models.CharField(max_length=20, unique=True)),
                ('complexity_txt', models.CharField(max_length=250)),
                ('created_user_id', models.CharField(max_length=250)),
                ('created_timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_user_id', models.CharField(max_length=250)),
                ('last_updated_timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'complexity_list',
            },
        ),
        migrations.CreateModel(
            name='QuizList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_id', models.CharField(max_length=20, unique=True)),
                ('quiz_name', models.CharField(max_length=250)),
                ('quiz_start_time', models.DateTimeField(blank=True)),
                ('quiz_end_time', models.DateTimeField(blank=True)),
                ('created_user_id', models.CharField(max_length=250)),
                ('created_timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_user_id', models.CharField(max_length=250)),
                ('last_updated_timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'quiz_list',
            },
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_id', models.CharField(max_length=250)),
                ('created_timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='QuestionManagement.QuestionBank')),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='QuizManagement.QuizList')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='UserManagement.UserList')),
            ],
            options={
                'db_table': 'quiz_result',
            },
        ),
        migrations.CreateModel(
            name='QuizQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_user_id', models.CharField(max_length=250)),
                ('created_timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_user_id', models.CharField(max_length=250)),
                ('last_updated_timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('complexity_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='QuizManagement.ComplexityList')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='QuestionManagement.QuestionBank')),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='QuizManagement.QuizList')),
            ],
            options={
                'db_table': 'quiz_questions',
            },
        ),
        migrations.CreateModel(
            name='QuizAttempts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=50)),
                ('mac_address', models.CharField(max_length=50)),
                ('created_timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='QuizManagement.QuizList')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='UserManagement.UserList')),
            ],
            options={
                'db_table': 'quiz_attempts',
            },
        ),
    ]
