# Generated by Django 2.2.1 on 2019-08-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizlist',
            name='quiz_id',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='quizlist',
            name='quiz_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='answer_id',
            field=models.CharField(max_length=30),
        ),
    ]
