# Generated by Django 2.2.1 on 2019-08-19 19:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoleList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.CharField(max_length=40, unique=True)),
                ('role_txt', models.CharField(max_length=250)),
                ('created_user_id', models.CharField(max_length=250)),
                ('created_timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_user_id', models.CharField(max_length=250)),
                ('last_updated_timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'role_list',
            },
        ),
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, unique=True)),
                ('user_name', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=36)),
                ('active_ind', models.CharField(max_length=1)),
                ('profile_pic', models.ImageField(upload_to='images\\<django.db.models.fields.CharField>')),
                ('created_user_id', models.CharField(max_length=250)),
                ('created_timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_user_id', models.CharField(max_length=250)),
                ('last_updated_timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('roe_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='UserManagement.RoleList')),
            ],
            options={
                'db_table': 'user_list',
            },
        ),
    ]
