# Generated by Django 2.2.1 on 2019-08-29 06:38

import UserManagement.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoleList',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_txt', models.CharField(max_length=250)),
                ('created_user_id', models.CharField(max_length=250)),
                ('created_timestamp', models.DateTimeField(auto_now=True)),
                ('updated_user_id', models.CharField(max_length=250)),
                ('last_updated_timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'role_list',
            },
        ),
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=64)),
                ('user_name', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=36)),
                ('active_ind', models.CharField(max_length=1)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to=UserManagement.models.get_image_path)),
                ('created_user_id', models.CharField(max_length=250)),
                ('created_timestamp', models.DateTimeField(auto_now=True)),
                ('updated_user_id', models.CharField(max_length=250)),
                ('last_updated_timestamp', models.DateTimeField(auto_now=True)),
                ('roe_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='UserManagement.RoleList')),
            ],
            options={
                'db_table': 'user_list',
            },
        ),
    ]
