# Generated by Django 2.2.1 on 2019-08-20 03:02

import UserManagement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlist',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=UserManagement.models.get_image_path),
        ),
    ]
